## Question 1:

In [62]:
import numpy as np
from scipy.optimize import minimize

In [63]:
def obj(xy):
    # xy[0] is Labor
    # xy[1] is Capital
    
    mac = -(0.05*(xy[0]**(2/3))*xy[1]**(1/3)) 
    
    
    return mac

In [64]:
best_loc = minimize(obj,[0,0],method='BFGS')
best_loc.x

array([0., 0.])

In [65]:
def confun(xy):
    return 12*xy[0]+15*xy[1] - 100000

In [66]:
constr1 = {'type':'eq', 'fun': confun}
# then we put all our constraint dictionaries into a list
constraints = [constr1]

In [67]:
best_loc_north = minimize(obj,[2000,5000],constraints=constraints)

In [68]:
best_loc_north.x

array([5555.39238936, 2222.35275518])

In [69]:
-best_loc_north.fun

204.66841641459064

## Question 2

In [160]:
import pandas as pd
stk = pd.read_csv("homework4stocks.csv")

In [161]:
stk

,Date,AA,AAPL,AXP,BA,CAT,CSCO,DD,DIS,EK,...,KO,MCD,MMM,MO,MRK,MSFT,PG,T,UTX,WMT
0,Jan-2004,-0.101,0.055,0.075,-0.009,-0.055,0.061,-0.043,0.029,0.107,...,-0.030,0.037,-0.070,0.021,0.030,0.010,0.017,-0.011,0.008,0.015
1,Feb-2004,0.101,0.060,0.031,0.043,-0.030,-0.099,0.035,0.105,0.005,...,0.015,0.099,-0.009,0.035,0.010,-0.040,0.014,-0.058,-0.032,0.106
2,Mar-2004,-0.074,0.130,-0.028,-0.053,0.044,0.018,-0.064,-0.058,-0.083,...,0.012,0.010,0.049,-0.043,-0.074,-0.060,0.023,0.022,-0.063,0.004
3,Apr-2004,-0.114,-0.047,-0.056,0.039,-0.012,-0.113,0.017,-0.078,-0.015,...,0.005,-0.047,0.056,0.017,0.064,0.048,0.014,0.028,-0.001,-0.045
4,May-2004,0.023,0.088,0.036,0.078,-0.031,0.070,0.014,0.019,0.025,...,0.015,-0.030,-0.018,-0.133,0.006,0.004,0.019,-0.048,-0.015,-0.020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Jan-2010,-0.211,-0.089,-0.067,0.120,-0.077,-0.061,-0.031,-0.084,0.434,...,-0.048,0.000,-0.026,0.012,0.045,-0.075,0.022,-0.082,-0.028,0.000
73,Feb-2010,0.047,0.065,0.014,0.049,0.092,0.083,0.047,0.057,-0.018,...,-0.028,0.031,0.002,0.013,-0.034,0.022,0.028,-0.022,0.024,0.012
74,Mar-2010,0.071,0.148,0.085,0.150,0.102,0.070,0.104,0.117,-0.025,...,0.052,0.045,0.043,0.038,0.023,0.022,0.000,0.042,0.072,0.034
75,Apr-2010,-0.057,0.111,0.118,-0.002,0.090,0.035,0.070,0.055,0.059,...,-0.028,0.058,0.061,0.033,-0.062,0.043,-0.010,0.025,0.018,-0.035
76,May-2010,-0.131,-0.016,-0.135,-0.109,-0.108,-0.140,-0.082,-0.093,-0.080,...,-0.038,-0.045,-0.100,-0.043,-0.039,-0.151,-0.017,-0.068,-0.096,-0.052

In [162]:
stk_mean = pd.DataFrame(stk.mean(), columns = ['mean'])
stk_var = pd.DataFrame(stk.std()**2, columns = ['variance'])

In [171]:
stk_cov=stk.drop('Date', axis = 1)
stk_cov

,AA,AAPL,AXP,BA,CAT,CSCO,DD,DIS,EK,FDX,...,KO,MCD,MMM,MO,MRK,MSFT,PG,T,UTX,WMT
0,-0.101,0.055,0.075,-0.009,-0.055,0.061,-0.043,0.029,0.107,-0.003,...,-0.030,0.037,-0.070,0.021,0.030,0.010,0.017,-0.011,0.008,0.015
1,0.101,0.060,0.031,0.043,-0.030,-0.099,0.035,0.105,0.005,0.021,...,0.015,0.099,-0.009,0.035,0.010,-0.040,0.014,-0.058,-0.032,0.106
2,-0.074,0.130,-0.028,-0.053,0.044,0.018,-0.064,-0.058,-0.083,0.095,...,0.012,0.010,0.049,-0.043,-0.074,-0.060,0.023,0.022,-0.063,0.004
3,-0.114,-0.047,-0.056,0.039,-0.012,-0.113,0.017,-0.078,-0.015,-0.043,...,0.005,-0.047,0.056,0.017,0.064,0.048,0.014,0.028,-0.001,-0.045
4,0.023,0.088,0.036,0.078,-0.031,0.070,0.014,0.019,0.025,0.023,...,0.015,-0.030,-0.018,-0.133,0.006,0.004,0.019,-0.048,-0.015,-0.020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,-0.211,-0.089,-0.067,0.120,-0.077,-0.061,-0.031,-0.084,0.434,-0.061,...,-0.048,0.000,-0.026,0.012,0.045,-0.075,0.022,-0.082,-0.028,0.000
73,0.047,0.065,0.014,0.049,0.092,0.083,0.047,0.057,-0.018,0.082,...,-0.028,0.031,0.002,0.013,-0.034,0.022,0.028,-0.022,0.024,0.012
74,0.071,0.148,0.085,0.150,0.102,0.070,0.104,0.117,-0.025,0.103,...,0.052,0.045,0.043,0.038,0.023,0.022,0.000,0.042,0.072,0.034
75,-0.057,0.111,0.118,-0.002,0.090,0.035,0.070,0.055,0.059,-0.036,...,-0.028,0.058,0.061,0.033,-0.062,0.043,-0.010,0.025,0.018,-0.035
76,-0.131,-0.016,-0.135,-0.109,-0.108,-0.140,-0.082,-0.093,-0.080,-0.072,...,-0.038,-0.045,-0.100,-0.043,-0.039,-0.151,-0.017,-0.068,-0.096,-0.052

In [173]:
cov_s= stk_cov.cov()
cov_s

,AA,AAPL,AXP,BA,CAT,CSCO,DD,DIS,EK,FDX,...,KO,MCD,MMM,MO,MRK,MSFT,PG,T,UTX,WMT
AA,0.013656,0.006025,0.007063,0.004233,0.008318,0.004408,0.005365,0.004893,0.004586,0.004916,...,0.002070,0.001884,0.003601,0.001283,0.002432,0.003552,0.001582,0.002696,0.003637,0.001022
AAPL,0.006025,0.014295,0.006367,0.003505,0.004729,0.003312,0.003641,0.003477,0.002872,0.003340,...,0.001133,0.002767,0.002614,0.002288,0.001295,0.003710,0.001251,0.002266,0.002393,-0.000312
AXP,0.007063,0.006367,0.017277,0.005524,0.008176,0.005145,0.007190,0.005690,0.004734,0.006812,...,0.001420,0.001436,0.004510,0.001823,0.001134,0.004006,0.002385,0.002160,0.004179,0.000773
BA,0.004233,0.003505,0.005524,0.006585,0.003458,0.002636,0.003765,0.003279,0.005510,0.002633,...,0.000982,0.001156,0.002239,0.001244,0.002613,0.001521,0.001063,0.000953,0.003095,0.000043
CAT,0.008318,0.004729,0.008176,0.003458,0.010547,0.004454,0.004997,0.004118,0.003857,0.005635,...,0.002025,0.001793,0.003412,0.000787,0.001137,0.002747,0.002305,0.002742,0.003426,0.000914
CSCO,0.004408,0.003312,0.005145,0.002636,0.004454,0.006239,0.003343,0.003171,0.002940,0.003255,...,0.001462,0.000805,0.002396,0.000569,0.001451,0.002552,0.001373,0.001678,0.002034,0.000421
DD,0.005365,0.003641,0.007190,0.003765,0.004997,0.003343,0.005926,0.003772,0.003683,0.003924,...,0.001206,0.001271,0.002797,0.001567,0.001835,0.001855,0.001279,0.001226,0.002760,0.001033
DIS,0.004893,0.003477,0.005690,0.003279,0.004118,0.003171,0.003772,0.004637,0.002549,0.002931,...,0.001433,0.001527,0.002031,0.001324,0.001623,0.001985,0.001097,0.000952,0.002446,0.000640
EK,0.004586,0.002872,0.004734,0.005510,0.003857,0.002940,0.003683,0.002549,0.022754,0.002976,...,0.000805,0.002389,0.002289,0.001276,0.003146,0.003594,0.001283,0.001283,0.002866,0.001622
FDX,0.004916,0.003340,0.006812,0.002633,0.005635,0.003255,0.003924,0.002931,0.002976,0.006042,...,0.001197,0.001042,0.003122,0.000287,0.000301,0.001662,0.001617,0.001598,0.002240,0.001225
GE,0.005268,0.003341,0.007702,0.004212,0.005746,0.003768,0.004918,0.003801,0.005254,0.004402,...,0.001976,0.001592,0.002824,0.001186,0.001608,0.002658,0.002239,0.001860,0.003095,0.000929
GT,0.010060,0.008153,0.015737,0.006319,0.009493,0.007273,0.009202,0.006262,0.005102,0.006384,...,0.001883,0.002254,0.005255,0.003487,0.001880,0.004333,0.003104,0.003257,0.004892,0.000558
HPQ,0.004464,0.002982,0.004221,0.002263,0.003973,0.003793,0.002513,0.002787,0.002909,0.002152,...,0.001043,0.001241,0.001657,0.000941,0.001427,0.002324,0.001334,0.001099,0.001931,0.000008
IBM,0.003084,0.002658,0.002617,0.001187,0.002294,0.002429,0.002477,0.001938,0.001582,0.001349,...,0.000807,0.001047,0.001270,0.001015,0.000691,0.001159,0.000594,0.000672,0.001269,0.000427
IP,0.010143,0.005084,0.015549,0.005670,0.008742,0.005021,0.008059,0.006481,0.005590,0.006508,...,0.001582,0.001777,0.004720,0.002207,0.002053,0.004213,0.002442,0.001589,0.004885,0.000754
JNJ,0.001764,0.001073,0.001798,0.001412,0.001391,0.001031,0.001593,0.001427,0.001803,0.000989,...,0.001085,0.000793,0.000899,0.000777,0.001491,0.001108,0.001026,0.000548,0.001214,0.000433
JPM,0.002925,0.001646,0.006495,0.002601,0.003339,0.002168,0.003872,0.002587,0.003574,0.003183,...,0.001253,0.001190,0.001470,0.000949,0.001029,0.001920,0.001444,0.000895,0.002530,0.001389
KO,0.002070,0.001133,0.001420,0.000982,0.002025,0.001462,0.001206,0.001433,0.000805,0.001197,...,0.002449,0.001072,0.001068,0.000510,0.001691,0.001373,0.001120,0.000852,0.000765,0.000462
MCD,0.001884,0.002767,0.001436,0.001156,0.001793,0.000805,0.001271,0.001527,0.002389,0.001042,...,0.001072,0.002530,0.000502,0.000580,0.001250,0.001504,0.001028,0.000835,0.001151,0.000624
MMM,0.003601,0.002614,0.004510,0.002239,0.003412,0.002396,0.002797,0.002031,0.002289,0.003122,...,0.001068,0.000502,0.003713,0.000853,0.000548,0.001002,0.001210,0.001050,0.001613,0.000245
MO,0.001283,0.002288,0.001823,0.001244,0.000787,0.000569,0.001567,0.001324,0.001276,0.000287,...,0.000510,0.000580,0.000853,0.002828,0.001141,0.000976,0.000624,0.000326,0.000962,-0.000492
MRK,0.002432,0.001295,0.001134,0.002613,0.001137,0.001451,0.001835,0.001623,0.003146,0.000301,...,0.001691,0.001250,0.000548,0.001141,0.006943,0.001954,0.001065,0.001243,0.001923,0.000268
MSFT,0.003552,0.003710,0.004006,0.001521,0.002747,0.002552,0.001855,0.001985,0.003594,0.001662,...,0.001373,0.001504,0.001002,0.000976,0.001954,0.004891,0.000836,0.001717,0.001593,0.000479
PG,0.001582,0.001251,0.002385,0.001063,0.002305,0.001373,0.001279,0.001097,0.001283,0.001617,...,0.001120,0.001028,0.001210,0.000624,0.001065,0.000836,0.002104,0.000809,0.001198,0.000068
T,0.002696,0.002266,0.002160,0.000953,0.002742,0.001678,0.001226,0.000952,0.001283,0.001598,...,0.000852,0.000835,0.001050,0.000326,0.001243,0.001717,0.000809,0.002831,0.001267,0.000348
UTX,0.003637,0.002393,0.004179,0.003095,0.003426,0.002034,0.002760,0.002446,0.002866,0.002240,...,0.000765,0.001151,0.001613,0.000962,0.001923,0.001593,0.001198,0.001267,0.002956,0.000328
WMT,0.001022,-0.000312,0.000773,0.000043,0.000914,0.000421,0.001033,0.000640,0.001622,0.001225,...,0.000462,0.000624,0.000245,-0.000492,0.000268,0.000479,0.000068,0.000348,0.000328,0.002137

## Question 3

In [2]:
import pandas as pd

In [6]:
var_sel = pd.read_csv('variable_selection.csv')

In [20]:
var_sel.drop('Unnamed: 0', axis = 1, inplace = True)

In [21]:
var_sel

            y        x1        x2         x3
0   42.412844  4.529686  7.172525  15.356190
1   24.820174  2.516030  4.377053   6.084709
2   26.617801  3.038386  4.411439  11.563392
3   21.329637  1.602293  4.225374   9.365461
4   34.183805  4.148982  5.618860   8.534010
..        ...       ...       ...        ...
95  24.656431  2.607587  4.077544  12.309712
96  39.280398  2.874912  7.871697  11.435131
97  30.085919  3.768077  4.622765  16.279047
98  31.639203  2.645656  5.991489   7.619829
99  31.644793  3.661710  5.133656  10.273976

[100 rows x 4 columns]

In [48]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [50]:
model1 = LinearRegression()
model2 = LinearRegression()
model3 = LinearRegression()
model4 = LinearRegression()
model5 = LinearRegression()
model6 = LinearRegression()

In [55]:
model1.fit(var_sel[['x1']],var_sel['y'])
model1.coef_
mean_squared_error(model1.predict(var_sel[['x1']]),var_sel['y'])

79.01299428781705

In [56]:
model2.fit(var_sel[['x2']],var_sel['y'])
model2.coef_
mean_squared_error(model2.predict(var_sel[['x2']]),var_sel['y'])

8.78835823252793

In [57]:
model3.fit(var_sel[['x3']],var_sel['y'])
model3.coef_
mean_squared_error(model3.predict(var_sel[['x3']]),var_sel['y'])

85.75635880480662

In [58]:
#least mSE
model4.fit(var_sel[['x1','x2']],var_sel['y'])
model4.coef_
mean_squared_error(model4.predict(var_sel[['x1','x2']]),var_sel['y'])

0.2619087330164184

In [59]:
model5.fit(var_sel[['x1','x3']],var_sel['y'])
model5.coef_
mean_squared_error(model5.predict(var_sel[['x1','x3']]),var_sel['y'])

78.60088759733235

In [60]:
model6.fit(var_sel[['x2','x3']],var_sel['y'])
model6.coef_
mean_squared_error(model6.predict(var_sel[['x2','x3']]),var_sel['y'])

8.781810504367627

## Question 4

In [80]:
nfl = pd.read_csv('nflratings.csv', header=None, names = ['Week','HTI','VTI','HTS','VTS'])

In [81]:
nfl

     Week  HTI  VTI  HTS  VTS
0       1   25   31   13   10
1       1    2   17   19    7
2       1   29   26   28    0
3       1   21   32   23   17
4       1    3   16   38   24
..    ...  ...  ...  ...  ...
251    17    5   20   23   10
252    17   11    6   23   37
253    17   22    6   37    0
254    17    8   15   23   17
255    17    1   12    7   33

[256 rows x 5 columns]

In [104]:
nfl['APS'] = nfl['HTS'] - nfl['VTS']

In [145]:
def obj(ratings):
    # xy[0] is Labor
    # xy[1] is Capital
    
    pred_spread = (ratings[nfl['HTI']] - ratings[nfl['VTI']] + ratings[32])
    pred_error = sum((pred_spread - nfl['APS'])**2)
    
    return pred_error

In [147]:
a = [85]*32 + [3]

In [148]:
best_loc = minimize(obj,a,method='BFGS')
best_loc.x

array([ 85.        ,   6.5588447 ,  11.87794045,  14.78218395,
         5.12548784,  10.7964538 ,   1.84852252,   9.58055942,
        -1.07648783,  14.15760958,   7.67224913,  -7.45943518,
        14.29208884,   9.0208102 ,  12.89884869,   0.47627356,
        -1.07532247,   8.65177967,  14.10133566,  18.15917403,
        17.66518625,   7.13535688,  15.1849121 ,  -2.93065292,
        12.9946306 ,   8.6788498 , -10.24357291,  14.64230808,
         7.2784307 ,  -3.23166167,   1.20758049,   4.22477864,
         2.17273573])

In [149]:
best_loc.fun

42925.679768715614

In [150]:
nfl['pred_spread'] = (best_loc.x[nfl['HTI']] - best_loc.x[nfl['VTI']] + best_loc.x[32])

In [151]:
nfl

     Week  HTI  VTI  HTS  VTS  APS  pred_spread
0       1   25   31   13   10    3     6.626807
1       1    2   17   19    7   12     5.398897
2       1   29   26   28    0   28     9.184647
3       1   21   32   23   17    6     7.135357
4       1    3   16   38   24   14    18.030242
..    ...  ...  ...  ...  ...  ...          ...
251    17    5   20   23   10   13    -4.695997
252    17   11    6   23   37  -14    -7.135222
253    17   22    6   37    0   37    15.509125
254    17    8   15   23   17    6     0.619974
255    17    1   12    7   33  -26    -5.560508

[256 rows x 7 columns]

In [154]:
nfl['a_win'] = np.where(nfl['APS'] > 0, 1,0)
nfl['p_win'] = np.where(nfl['pred_spread'] > 0, 1,0)

In [155]:
nfl

     Week  HTI  VTI  HTS  VTS  APS  pred_spread  a_win  p_win
0       1   25   31   13   10    3     6.626807      1      1
1       1    2   17   19    7   12     5.398897      1      1
2       1   29   26   28    0   28     9.184647      1      1
3       1   21   32   23   17    6     7.135357      1      1
4       1    3   16   38   24   14    18.030242      1      1
..    ...  ...  ...  ...  ...  ...          ...    ...    ...
251    17    5   20   23   10   13    -4.695997      1      0
252    17   11    6   23   37  -14    -7.135222      0      0
253    17   22    6   37    0   37    15.509125      1      1
254    17    8   15   23   17    6     0.619974      1      1
255    17    1   12    7   33  -26    -5.560508      0      0

[256 rows x 9 columns]

In [156]:
sum(nfl['a_win'] == nfl['p_win'])

181